#!/usr/bin/env bash

set -e

export LIBRARY_PATH="$LIBRARY_PATH:$HOME/.local/lib"

meson setup --reconfigure --prefix="$(pwd)/builddir/installdir" --buildtype debug builddir .
ninja -C builddir install
