#!/usr/bin/env bash

set -eo pipefail

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  TESTS_FOLDER="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$TESTS_FOLDER/$SOURCE"
done
TESTS_FOLDER="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
unset SOURCE

if [ "$(uname)"  != "Darwin" ]; then
  SOEXT= ".so"
else
  SOEXT=".dylib"
fi
PLUGIN=$(find $(pwd) -name "libldclint*$SOEXT" | head -1)
if [ "x$PLUGIN" == "x" ]; then
  echo Failing to locate the ldclint plugin >/dev/stderr
  exit 1;
fi
export LDCLINT_SO=$PLUGIN
lit "$TESTS_FOLDER" -v
